export const listBank: any[] = [
    { name: 'ธนาคารกรุงเทพ', code: 'BBL', src: 'assets/image/bank/BBL.png', color: "#213E9A", color2: "#0B2360" },
    { name: 'ธนาคารเกียรตินาคิน', code: 'KKP', src: 'assets/image/bank/k.png', color: "#0090C3", color2: "#ธนาคารเกียรตินาคิน" },
    { name: 'ธนาคารไอซีบีซี', code: 'ICBC', src: 'assets/image/bank/cimb.png', color: "#ED1D24", color2: "#790008" },
    { name: 'ธนาคารกสิกรไทย', code: 'KBANK', src: 'assets/image/bank/kasikron.png', color: "#00A950", color2: "#ED1B2E" },
    { name: 'ธนาคารกรุงศรีอยุธยา', code: 'BAY', src: 'assets/image/bank/kongse.png', color: "#FEC323", color2: "#775708" },
    { name: 'ธนาคารกรุงไทย', code: 'KTB', src: 'assets/image/bank/kongthai.png', color: "#00A1E6", color2: "#005877" },
    { name: 'ธนาคารออมสิน', code: 'GSB', src: 'assets/image/bank/onsin.png', color: "#EC038B", color2: "#AF7E08" },
    { name: 'ธนาคารไทยพาณิชย์', code: 'SCB', src: 'assets/image/bank/scb.png', color: "#4E2A82", color2: "#311066" },
    { name: 'สแตนดาร์ดชาร์เตอร์ด', code: 'SC', src: 'assets/image/bank/standart.png', color: "#0075A3", color2: "#21A149" },
    { name: 'ธนาคารธนชาต', code: 'TCB', src: 'assets/image/bank/tanachai.png', color: "#F37636", color2: "#292929" },
    { name: 'ธนาคารทหารไทย', code: 'TMB', src: 'assets/image/bank/tmb.png', color: "#00A1E6", color2: "#C7303A" },
    { name: 'ธนาคารยูโอบี', code: 'UOB', src: 'assets/image/bank/uob.png', color: "#0A3166", color2: "#011B38" },
    { name: 'True Money Wallet', code: 'TMW', src: 'assets/image/bank/TMW.png', color: "#FDCD00", color2: "#FC8103" },
    { name: 'ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร', code: 'BAAC', src: 'assets/image/bank/BAAC.png', color: "#1a0dab", color2: "#a7872a" },
];
